# Generated by Django 3.1.7 on 2021-03-30 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('status', models.IntegerField(choices=[(0, 'Выполнено'), (1, 'Активно'), (2, 'Отложено')], default=1, verbose_name='Статус задачи')),
                ('author', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
