# Generated by Django 3.1.7 on 2021-03-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 19, 1, 53, 739095)),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
    ]
