# Generated by Django 3.1.7 on 2021-04-14 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210413_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 16, 11, 52, 693624), verbose_name='Когда выполнить'),
        ),
    ]
